# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew fatJar
      - name: Commit Updated JAR
          uses: actions/checkout@v2
          with:
            run: |
              git config --global user.email "${GITHUB_USERNAME}@users.noreply.github.com"
              git config --global user.name "${GITHUB_USERNAME}"
              git pull origin ${GITHUB_BRANCH##*/}
              mv build/libs/*-all.jar .
              git add *.jar
              git commit -m "Update Jar File"
              git push -u origin main
          env:
            GITHUB_BRANCH: ${{ github.head_ref }}
            GITHUB_USERNAME: ${{ github.actor }}